before_script:
  - export BASE_VERSION=0.0.2
  - export DEV_RELEASE_SEGMENT=.dev$TRAVIS_BUILD_NUMBER
  - export CLI_VERSION=$BASE_VERSION$DEV_RELEASE_SEGMENT
  - export DOCKER_TAGGED_BASE_IMAGE=turingarena/turingarena-base:travis-$TRAVIS_BUILD_NUMBER
  - export DOCKER_IMAGE=turingarena/turingarena:v$BASE_VERSION$DEV_RELEASE_SEGMENT
  - export SERVERLESS_STAGE=branch-$(echo $TRAVIS_BRANCH | tr -d -c '[:alpha:]-')
  - export HYPERSH_FUNC_NAME=evaluate-$TRAVIS_BRANCH

sudo: required

language: python
python:
  - "3.6"

services:
  - docker

cache: yarn

install:
  - wget https://hyper-install.s3.amazonaws.com/hyper-linux-x86_64.tar.gz
  - tar xzf hyper-linux-x86_64.tar.gz -C $TRAVIS_BUILD_DIR
  - npm install -g serverless
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - >
    $TRAVIS_BUILD_DIR/hyper
    config
    --default-region=us-west-1
    --accesskey=$HYPERSH_ACCESS_KEY
    --secretkey=$HYPERSH_SECRET_KEY

stages:
  - base_build
  - build
  - deploy

jobs:
  include:
    - if: type == api AND commit_message =~ /update-base/
      stage: base_build
      script:
        - docker build -t $DOCKER_TAGGED_BASE_IMAGE -f Dockerfile.base .
        - docker push $DOCKER_TAGGED_BASE_IMAGE
    - stage: build
      script:
        - env > env
        - >
          docker build
          --network none
          --build-arg BASE_IMAGE=$DOCKER_BASE_IMAGE
          -t $DOCKER_IMAGE
          .
        - docker push $DOCKER_IMAGE
        - docker build -t deploy deploy/
        - HYPER_FUNC_ID=$(docker run --rm --env-file env deploy)
        - cd backend/
        - npm install
        - serverless deploy --stage $SERVERLESS_STAGE
    - stage: deploy
      script:
        - pip install --upgrade setuptools twine wheel
        - cd cli/
        - echo "VERSION='$CLI_VERSION'" > turingarena_common/build_version.py
        - python setup.py egg_info bdist_wheel
        - twine upload dist/*
