sudo: required

services:
  - docker

cache:
  yarn

script:
  - docker run turingarena/turingarena test /turingarena
  - cd web/ && yarn && yarn build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: web/build/
  repo: turingarena/demo
  target-branch: master
  verbose: true
  on:
    branch: master
