before_script:
  - export BASE_VERSION=0.0.2
  - export DEV_RELEASE_SEGMENT=.dev$TRAVIS_BUILD_NUMBER
  - export CLI_VERSION=$BASE_VERSION$DEV_RELEASE_SEGMENT
  - export DOCKER_TAGGED_BASE_IMAGE=turingarena/turingarena-base:travis-$TRAVIS_BUILD_NUMBER
  - export DOCKER_IMAGE=turingarena/turingarena:v$BASE_VERSION$DEV_RELEASE_SEGMENT
  - export SERVERLESS_STAGE=branch-$(echo $TRAVIS_BRANCH | tr -d -c '[:alpha:]-')
  - export HYPERSH_FUNC_NAME=evaluate-$TRAVIS_BRANCH
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

sudo: required

language: python
python:
  - "3.6"

services:
  - docker

cache: yarn

stages:
  - base_build
  - build
  - deploy

jobs:
  include:
    - if: type == api AND commit_message =~ /update-base/
      stage: base_build
      script:
        - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        - docker build -t $DOCKER_TAGGED_BASE_IMAGE -f Dockerfile.base .
        - docker push $DOCKER_TAGGED_BASE_IMAGE
    - stage: build
      script:
        - env > .env
        - docker build --network none --build-arg BASE_IMAGE=$DOCKER_BASE_IMAGE -t $DOCKER_IMAGE .
        - docker push $DOCKER_IMAGE
        - docker build --build-arg TURINGARENA_IMAGE=$DOCKER_IMAGE -t deploy deploy/
        - docker run --rm --env-file .env deploy
