sudo: required
language: bash

services:
  - docker

cache: yarn

script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - >
    docker build
    -t turingarena/turingarena-base:$TRAVIS_BRANCH
    -f Dockerfile.base
    .
  - docker push turingarena/turingarena-base:$TRAVIS_BRANCH
  - >
    docker build
    --network none
    --build-arg BASE_IMAGE=turingarena/turingarena-base:$TRAVIS_BRANCH
    -t turingarena/turingarena:$TRAVIS_BRANCH
    .
  - docker push turingarena/turingarena:$TRAVIS_BRANCH
  - >
    docker run
    --rm
    turingarena/turingarena:$TRAVIS_BRANCH
    test /usr/local/turingarena/turingarena

deploy:
- provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: web/build/
  repo: turingarena/demo
  target-branch: master
  verbose: true
  on:
    branch: master
- provider: pypi
  before_deploy: cd cli/
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  on:
    branch: develop
