sudo: required

language: python
python:
  - "3.6"

services:
  - docker

cache: yarn

git:
  depth: 9999999 # needed for automatic versioning

jobs:
  include:
    - if: branch = develop
      script:
      - pip install --upgrade setuptools twine wheel
      - cd cli/
      - python setup.py bdist_wheel
      - twine upload dist/*
    - if: branch = develop
      script:
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - >
        docker build
        -t turingarena/turingarena-base:latest
        -f Dockerfile.base
        .
      - docker push turingarena/turingarena-base:latest
      - >
        docker build
        --network none
        --build-arg BASE_IMAGE=turingarena/turingarena-base:latest
        -t turingarena/turingarena:latest
        .
      - docker push turingarena/turingarena:latest

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: false
    local-dir: web/build/
    repo: turingarena/demo
    target-branch: master
    verbose: true
    on:
      branch: master