sudo: required
language: bash
services:
  - docker

before_script:
  - export BASE_VERSION=0.0.2
  - export DEV_RELEASE_SEGMENT=.dev$TRAVIS_BUILD_NUMBER
  - export CLI_VERSION=$BASE_VERSION$DEV_RELEASE_SEGMENT
  - export DOCKER_TAGGED_BASE_IMAGE=turingarena/turingarena-base:travis-$TRAVIS_BUILD_NUMBER
  - export DOCKER_DEPLOY_TAGGED_BASE_IMAGE=turingarena/turingarena-deploy:travis-$TRAVIS_BUILD_NUMBER
  - export BRANCH_SEGMENT=$(echo $TRAVIS_BRANCH | tr -d -c '[:alpha:]-')
  - export DOCKER_IMAGE=turingarena/turingarena:$BRANCH_SEGMENT
  - export SERVERLESS_STAGE=branch-$BRANCH_SEGMENT
  - export HYPERSH_FUNC_NAME=evaluate-$BRANCH_SEGMENT
  - export SURGE_DOMAIN=turingarena-$BRANCH_SEGMENT.surge.sh
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

jobs:
  include:
    - if: type == api AND commit_message =~ /update-base/
      script:
        - >
          docker build
          -t $DOCKER_TAGGED_BASE_IMAGE
          .
          -f docker/base.dockerfile
        - docker push $DOCKER_TAGGED_BASE_IMAGE
    - if: type == api AND commit_message =~ /update-deploy-base/
      script:
        - >
          docker build
          -t $DOCKER_DEPLOY_TAGGED_BASE_IMAGE
          .
          -f deploy/base.docekrfile
        - docker push $DOCKER_DEPLOY_TAGGED_BASE_IMAGE
    - if: type == push
      script:
        - >
            docker build
            --network none
            --build-arg BASE_IMAGE=$DOCKER_BASE_IMAGE
            -t $DOCKER_IMAGE
            .
            -f docker/main.dockerfile
        - docker push $DOCKER_IMAGE
        - >
            docker build
            --build-arg BASE_IMAGE=$DEPLOY_BASE_IMAGE
            -t deploy
            .
            -f deploy/main.dockerfile
        - docker run --rm --env-file deploy/list.env deploy sh /src/deploy/deploy-cloud.sh
        - docker run --rm --env-file deploy/list.env deploy sh /src/deploy/publish-pip-dev.sh
        - if [ "$TRAVIS_BRANCH" == 'cli-stable' ] ;
          then docker run --rm --env-file deploy/list.env deploy sh /src/deploy/publish-pip-cli.sh
          fi
