sudo: required

cache:
  yarn

script:
  - cd web/ && yarn && yarn build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: web/build/
  repo: turingarena/demo
  target-branch: master
  verbose: true
  on:
    branch: master
