version: '3'
services:
  turingarena:
    image: turingarena/turingarena
    read_only: true
    volumes:
      - ./:/usr/local/turingarena/:ro
    tmpfs:
      - /run/turingarena:exec,mode=1777
      - /tmp:exec,mode=1777
    entrypoint: /usr/sbin/sshd
    command: -D -e -o PermitEmptyPasswords=yes -o Protocol=2
    ports:
      - "127.0.0.1:20122:22"
