version: '3'
services:
  turingarena:
    image: turingarena/turingarena
    read_only: true
    volumes:
      - ./:/usr/local/turingarena/:ro
    tmpfs:
      - /run:exec,mode=777
      - /tmp:exec,mode=777
    entrypoint:
      - socat
    command:
      - TCP-LISTEN:22,fork
      - EXEC:/usr/sbin/sshd -i -e -o PermitEmptyPasswords=yes -o PermitRootLogin=yes -o Protocol=2,nofork
    expose:
      - 22
  sshd_proxy:
    image: turingarena/turingarena
    read_only: true
    volumes:
      - /run/turingarena:/run/turingarena
    entrypoint:
      - socat
    command:
      - UNIX-LISTEN:/run/turingarena/sshd.sock,fork,mode=0666,reuseaddr
      - TCP:turingarena:22
