service: turingarena

plugins:
  #- serverless-python-requirements
  - serverless-apigw-binary

provider:
  name: aws
  runtime: python3.6
  timeout: 10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        Fn::GetAtt:
          - EvaluationEventsTable
          - Arn

package:
  individually: true
  excludeDevDependencies: false

functions:
  apihandler:
    package:
      exclude:
        - "**"
      include:
        - "turingarena_impl/**"
        - "turingarena_common/**"
        - "turingarena_cli/**"
    handler: turingarena_impl.api.lambda_proxy.main
    events:
      - http: ANY /{proxy+}
    environment:
      HYPERSH_REGION: us-west-1
      HYPERSH_FUNC_NAME: ${env:HYPERSH_FUNC_NAME}
      HYPERSH_FUNC_ID: ${env:HYPERSH_FUNC_ID}
      DYNAMODB_EVALUATION_EVENTS_TABLE: turingarena-${opt:stage, 'dev'}-EvaluationEventsTable

custom:
  apigwBinary:
    types:
      - 'multipart/form-data'
  pythonRequirements:
    fileName: lambda-requirements.txt

resources:
  Resources:
    EvaluationEventsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: turingarena-${opt:stage, 'dev'}-EvaluationEventsTable
        AttributeDefinitions:
          - AttributeName: evaluation_id
            AttributeType: S
          - AttributeName: index
            AttributeType: N
        KeySchema:
          - AttributeName: evaluation_id
            KeyType: HASH
          - AttributeName: index
            KeyType: RANGE
        TimeToLiveSpecification:
          Enabled: true
          AttributeName: expires
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
