service: turingarena

provider:
  name: aws
  runtime: python3.6

plugins:
  #- serverless-python-requirements
  - serverless-apigw-binary

package:
  individually: true
  excludeDevDependencies: false

functions:
  apihandler:
    package:
      exclude:
        - "**"
      include:
        - "turingarena_impl/**"
    handler: turingarena_impl.api.lambda_proxy.main
    events:
      - http: ANY /{proxy+}

custom:
  apigwBinary:
    types:
      - 'multipart/form-data'
  pythonRequirements:
    fileName: lambda-requirements.txt

resources:
  Resources:
    SubmissionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: SubmissionsTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        TimeToLiveSpecification:
          Enabled: true
          AttributeName: expires
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
